name: example
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  object_box_e2m:
    path: ../
  common_sdk:
    git:
      url: https://github.com/virnavi/flutter_starter.git
      ref: v0.0.4
      path: common_sdk
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.3.0


flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
