name: object_box_e2m
description: "A new Flutter project."
version: 0.0.3
homepage:
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.4.0"

dependencies:
  flutter:
    sdk: flutter
  common_sdk:
    git:
      url: https://github.com/virnavi/flutter_starter.git
      ref: v0.0.4
      path: common_sdk

  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.3.0


flutter:

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
